[workspace]
authors = ["Nathan Ward <nathan.ward@siriusxm.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "yap"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "mojo test -I src test"

[dependencies]
mojo = ">=25.6.0.dev2025081318,<26"
